# Generated by Django 4.1.7 on 2023-03-04 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ListPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("html", models.TextField(blank=True, default="")),
                ("title", models.CharField(default="", max_length=100)),
                ("last_visited", models.DateTimeField(blank=True, null=True)),
                (
                    "response_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("institution", models.CharField(default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="DetailPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("html", models.TextField(blank=True, default="")),
                ("title", models.CharField(default="", max_length=100)),
                ("last_visited", models.DateTimeField(blank=True, null=True)),
                (
                    "response_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collect.listpage",
                    ),
                ),
            ],
        ),
    ]
