# Generated by Django 4.1.7 on 2023-03-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collect", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailpage",
            name="attribution",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="detailpage",
            name="title",
            field=models.CharField(default="", max_length=500),
        ),
    ]
