# Generated by Django 4.1.7 on 2023-03-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collect", "0002_detailpage_attribution_alter_detailpage_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributionToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ("value",),
            },
        ),
        migrations.AlterModelOptions(
            name="listpage",
            options={"ordering": ("institution", "url")},
        ),
        migrations.AddField(
            model_name="detailpage",
            name="tokens",
            field=models.ManyToManyField(to="collect.attributiontoken"),
        ),
    ]
