# Generated by Django 4.1.7 on 2023-03-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collect", "0003_attributiontoken_alter_listpage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailpage",
            name="is_candidate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="detailpage",
            name="reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
