# Generated by Django 4.1.7 on 2023-03-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collect", "0005_remove_detailpage_is_candidate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailpage",
            name="artist_name",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="detailpage",
            name="year",
            field=models.CharField(default="", max_length=50),
        ),
    ]
