# Generated by Django 4.1.7 on 2023-03-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collect", "0006_detailpage_artist_name_detailpage_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailpage",
            name="parsed",
            field=models.BooleanField(default=False),
        ),
    ]
