# Generated by Django 4.1.4 on 2022-12-26 06:58

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=150, verbose_name="Full Name"),
                ),
                ("answer", models.CharField(max_length=200, verbose_name="Answer")),
            ],
        ),
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        upload_to=game.models.artwork_image_path, verbose_name="Image"
                    ),
                ),
                (
                    "featured",
                    models.DateField(unique=True, verbose_name="Next featured date"),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.artist"
                    ),
                ),
            ],
        ),
    ]
