# Generated by Django 4.1.6 on 2023-02-12 07:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(2023, 2, 12, 7, 53, 36, 694044),
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artwork",
            name="year",
            field=models.PositiveSmallIntegerField(default=1970, verbose_name="Year"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="artwork",
            name="featured",
            field=models.DateField(
                default=game.models.get_next_featured,
                unique=True,
                verbose_name="Next featured date",
            ),
        ),
    ]
