# Generated by Django 4.1.7 on 2023-03-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_alter_artist_answer_alter_artwork_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="artwork",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="artist",
            name="answer_slug",
            field=models.SlugField(
                default="", max_length=150, verbose_name="Answer Slug"
            ),
            preserve_default=False,
        ),
    ]
