# Generated by Django 4.1.7 on 2023-03-19 09:03

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ("collect", "0005_remove_detailpage_is_candidate_and_more"),
        ("game", "0005_alter_artist_options_alter_artwork_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtworkImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.URLField()),
                ("image", models.ImageField(upload_to=game.models.get_image_path)),
                (
                    "artwork",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.artwork",
                    ),
                ),
                (
                    "detailpage",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collect.detailpage",
                    ),
                ),
            ],
        ),
    ]
