# Generated by Django 4.1.7 on 2023-03-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_artworkimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="image",
        ),
    ]
