# Generated by Django 4.1.7 on 2023-03-20 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("collect", "0006_detailpage_artist_name_detailpage_year"),
        ("game", "0007_remove_artwork_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artworkimage",
            name="artwork",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.artwork",
            ),
        ),
        migrations.AlterField(
            model_name="artworkimage",
            name="detailpage",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collect.detailpage",
            ),
        ),
    ]
