# Generated by Django 4.2.2 on 2023-11-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_alter_artworkimage_artwork_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="name_slug",
            field=models.CharField(
                default="", max_length=150, verbose_name="Name Slug"
            ),
        ),
    ]
