# Generated by Django 4.2.2 on 2023-11-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_artist_name_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="answer_slug",
        ),
        migrations.AlterField(
            model_name="artist",
            name="name_slug",
            field=models.SlugField(
                default="", max_length=150, verbose_name="Name Slug"
            ),
        ),
    ]
