# Generated by Django 4.2.2 on 2024-01-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_alter_artist_name_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="artworkimage",
            name="average_hash",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="artworkimage",
            name="dhash",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="artworkimage",
            name="phash",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="artworkimage",
            name="whash",
            field=models.BigIntegerField(default=0),
        ),
    ]
