# Generated by Django 4.2.2 on 2024-01-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_remove_artworkimage_average_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artworkimage",
            name="average_hash",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AddField(
            model_name="artworkimage",
            name="dhash",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AddField(
            model_name="artworkimage",
            name="phash",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AddField(
            model_name="artworkimage",
            name="whash",
            field=models.CharField(default="", max_length=16),
        ),
    ]
